# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_View.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_View(object):
    def setupUi(self, View):
        View.setObjectName("View")
        View.resize(760, 570)
        View.setMinimumSize(QtCore.QSize(760, 570))
        View.setMaximumSize(QtCore.QSize(760, 570))
        self.stackedWidget = QtWidgets.QStackedWidget(View)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 751, 571))
        self.stackedWidget.setMaximumSize(QtCore.QSize(760, 16777215))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setLineWidth(5)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setObjectName("page_0")
        self.title_label = QtWidgets.QLabel(self.page_0)
        self.title_label.setGeometry(QtCore.QRect(310, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("")
        self.title_label.setWordWrap(False)
        self.title_label.setObjectName("title_label")
        self.page1_nextBtn = QtWidgets.QPushButton(self.page_0)
        self.page1_nextBtn.setGeometry(QtCore.QRect(630, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page1_nextBtn.setFont(font)
        self.page1_nextBtn.setStyleSheet("QPushButton\n"
"{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
"  transition: all 0.5s;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.page1_nextBtn.setObjectName("page1_nextBtn")
        self.textBrowser = QtWidgets.QTextBrowser(self.page_0)
        self.textBrowser.setGeometry(QtCore.QRect(110, 110, 531, 311))
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setStyleSheet("#title_label {\n"
"background-color: transparent;\n"
"}\n"
".QTextBrowser{\n"
"background-color: transparent;\n"
"}")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textBrowser.setLineWidth(0)
        self.textBrowser.setPlaceholderText("")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.raise_()
        self.page1_nextBtn.raise_()
        self.title_label.raise_()
        self.stackedWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.addfilebutton = QtWidgets.QPushButton(self.page_1)
        self.addfilebutton.setGeometry(QtCore.QRect(325, 90, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.addfilebutton.setFont(font)
        self.addfilebutton.setStyleSheet("QPushButton\n"
"{\n"
" background-color:    #0080ff;\n"
"color:white;\n"
" border-style: solid;\n"
" border-width:p0x;\n"
" border-radius:50px;\n"
" max-width:100px;\n"
" max-height:100px;\n"
" min-width:100px;\n"
" min-height:100px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.addfilebutton.setObjectName("addfilebutton")
        self.page2_nextBtn = QtWidgets.QPushButton(self.page_1)
        self.page2_nextBtn.setGeometry(QtCore.QRect(630, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page2_nextBtn.setFont(font)
        self.page2_nextBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.page2_nextBtn.setStyleSheet("QPushButton\n"
"{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
"  transition: all 0.5s;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.page2_nextBtn.setObjectName("page2_nextBtn")
        self.page2_backBtn = QtWidgets.QPushButton(self.page_1)
        self.page2_backBtn.setGeometry(QtCore.QRect(20, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page2_backBtn.setFont(font)
        self.page2_backBtn.setStyleSheet("QPushButton{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
"  transition: all 0.5s;\n"
"color: white;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.page2_backBtn.setObjectName("page2_backBtn")
        self.addFile_direction = QtWidgets.QLabel(self.page_1)
        self.addFile_direction.setGeometry(QtCore.QRect(200, 230, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addFile_direction.setFont(font)
        self.addFile_direction.setObjectName("addFile_direction")
        self.small_title_text_2 = QtWidgets.QLabel(self.page_1)
        self.small_title_text_2.setGeometry(QtCore.QRect(350, 0, 61, 16))
        self.small_title_text_2.setObjectName("small_title_text_2")
        self.file_status_label = QtWidgets.QLabel(self.page_1)
        self.file_status_label.setGeometry(QtCore.QRect(200, 270, 47, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.file_status_label.setFont(font)
        self.file_status_label.setObjectName("file_status_label")
        self.file_status = QtWidgets.QLabel(self.page_1)
        self.file_status.setGeometry(QtCore.QRect(240, 270, 331, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.file_status.setFont(font)
        self.file_status.setObjectName("file_status")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.line = QtWidgets.QFrame(self.page_2)
        self.line.setGeometry(QtCore.QRect(360, 30, 20, 481))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.output_title = QtWidgets.QLabel(self.page_2)
        self.output_title.setGeometry(QtCore.QRect(90, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.output_title.setFont(font)
        self.output_title.setObjectName("output_title")
        self.analytics_title = QtWidgets.QLabel(self.page_2)
        self.analytics_title.setGeometry(QtCore.QRect(520, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.analytics_title.setFont(font)
        self.analytics_title.setObjectName("analytics_title")
        self.custom_direct = QtWidgets.QLabel(self.page_2)
        self.custom_direct.setGeometry(QtCore.QRect(40, 60, 291, 21))
        self.custom_direct.setObjectName("custom_direct")
        self.Ana_direct = QtWidgets.QLabel(self.page_2)
        self.Ana_direct.setGeometry(QtCore.QRect(480, 52, 161, 21))
        self.Ana_direct.setObjectName("Ana_direct")
        self.small_title_text = QtWidgets.QLabel(self.page_2)
        self.small_title_text.setGeometry(QtCore.QRect(350, 0, 61, 16))
        self.small_title_text.setObjectName("small_title_text")
        self.cust_pval_check = QtWidgets.QCheckBox(self.page_2)
        self.cust_pval_check.setEnabled(True)
        self.cust_pval_check.setGeometry(QtCore.QRect(40, 90, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cust_pval_check.setFont(font)
        self.cust_pval_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.cust_pval_check.setIconSize(QtCore.QSize(50, 50))
        self.cust_pval_check.setCheckable(True)
        self.cust_pval_check.setObjectName("cust_pval_check")
        self.cust_actType_check = QtWidgets.QCheckBox(self.page_2)
        self.cust_actType_check.setEnabled(True)
        self.cust_actType_check.setGeometry(QtCore.QRect(40, 120, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cust_actType_check.setFont(font)
        self.cust_actType_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.cust_actType_check.setIconSize(QtCore.QSize(50, 50))
        self.cust_actType_check.setCheckable(True)
        self.cust_actType_check.setObjectName("cust_actType_check")
        self.cust_illuscore_check = QtWidgets.QCheckBox(self.page_2)
        self.cust_illuscore_check.setEnabled(True)
        self.cust_illuscore_check.setGeometry(QtCore.QRect(40, 150, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cust_illuscore_check.setFont(font)
        self.cust_illuscore_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.cust_illuscore_check.setIconSize(QtCore.QSize(50, 50))
        self.cust_illuscore_check.setCheckable(True)
        self.cust_illuscore_check.setObjectName("cust_illuscore_check")
        self.cust_active_score = QtWidgets.QCheckBox(self.page_2)
        self.cust_active_score.setEnabled(True)
        self.cust_active_score.setGeometry(QtCore.QRect(40, 180, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cust_active_score.setFont(font)
        self.cust_active_score.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.cust_active_score.setIconSize(QtCore.QSize(50, 50))
        self.cust_active_score.setCheckable(True)
        self.cust_active_score.setObjectName("cust_active_score")
        self.ana_dis_check = QtWidgets.QCheckBox(self.page_2)
        self.ana_dis_check.setEnabled(True)
        self.ana_dis_check.setGeometry(QtCore.QRect(410, 90, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ana_dis_check.setFont(font)
        self.ana_dis_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.ana_dis_check.setIconSize(QtCore.QSize(50, 50))
        self.ana_dis_check.setCheckable(True)
        self.ana_dis_check.setObjectName("ana_dis_check")
        self.ana_sum_check = QtWidgets.QCheckBox(self.page_2)
        self.ana_sum_check.setEnabled(True)
        self.ana_sum_check.setGeometry(QtCore.QRect(410, 120, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ana_sum_check.setFont(font)
        self.ana_sum_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.ana_sum_check.setIconSize(QtCore.QSize(50, 50))
        self.ana_sum_check.setCheckable(True)
        self.ana_sum_check.setObjectName("ana_sum_check")
        self.ana_mean_check = QtWidgets.QCheckBox(self.page_2)
        self.ana_mean_check.setEnabled(True)
        self.ana_mean_check.setGeometry(QtCore.QRect(410, 150, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ana_mean_check.setFont(font)
        self.ana_mean_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.ana_mean_check.setIconSize(QtCore.QSize(50, 50))
        self.ana_mean_check.setCheckable(True)
        self.ana_mean_check.setObjectName("ana_mean_check")
        self.ana_median_check = QtWidgets.QCheckBox(self.page_2)
        self.ana_median_check.setEnabled(True)
        self.ana_median_check.setGeometry(QtCore.QRect(410, 180, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ana_median_check.setFont(font)
        self.ana_median_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.ana_median_check.setIconSize(QtCore.QSize(50, 50))
        self.ana_median_check.setCheckable(True)
        self.ana_median_check.setObjectName("ana_median_check")
        self.ana_std_check = QtWidgets.QCheckBox(self.page_2)
        self.ana_std_check.setEnabled(True)
        self.ana_std_check.setGeometry(QtCore.QRect(410, 210, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ana_std_check.setFont(font)
        self.ana_std_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.ana_std_check.setIconSize(QtCore.QSize(50, 50))
        self.ana_std_check.setCheckable(True)
        self.ana_std_check.setObjectName("ana_std_check")
        self.ana_centchange_check = QtWidgets.QCheckBox(self.page_2)
        self.ana_centchange_check.setEnabled(True)
        self.ana_centchange_check.setGeometry(QtCore.QRect(410, 240, 289, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ana_centchange_check.setFont(font)
        self.ana_centchange_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.ana_centchange_check.setIconSize(QtCore.QSize(50, 50))
        self.ana_centchange_check.setCheckable(True)
        self.ana_centchange_check.setObjectName("ana_centchange_check")
        self.ana_specperc_check = QtWidgets.QCheckBox(self.page_2)
        self.ana_specperc_check.setEnabled(True)
        self.ana_specperc_check.setGeometry(QtCore.QRect(410, 270, 211, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ana_specperc_check.setFont(font)
        self.ana_specperc_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.ana_specperc_check.setIconSize(QtCore.QSize(50, 50))
        self.ana_specperc_check.setCheckable(True)
        self.ana_specperc_check.setObjectName("ana_specperc_check")
        self.ana_specint_check = QtWidgets.QCheckBox(self.page_2)
        self.ana_specint_check.setEnabled(True)
        self.ana_specint_check.setGeometry(QtCore.QRect(410, 300, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ana_specint_check.setFont(font)
        self.ana_specint_check.setStyleSheet("QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: black;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"background-color : #0080ff;\n"
"}\n"
"\n"
"\n"
"")
        self.ana_specint_check.setIconSize(QtCore.QSize(50, 50))
        self.ana_specint_check.setCheckable(True)
        self.ana_specint_check.setObjectName("ana_specint_check")
        self.page3_backBtn = QtWidgets.QPushButton(self.page_2)
        self.page3_backBtn.setGeometry(QtCore.QRect(20, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page3_backBtn.setFont(font)
        self.page3_backBtn.setStyleSheet("QPushButton\n"
"{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
" \n"
"color: white;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"\n"
"}")
        self.page3_backBtn.setObjectName("page3_backBtn")
        self.bioset_text = QtWidgets.QLabel(self.page_2)
        self.bioset_text.setGeometry(QtCore.QRect(40, 230, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.bioset_text.setFont(font)
        self.bioset_text.setObjectName("bioset_text")
        self.bioset_val_input = QtWidgets.QSpinBox(self.page_2)
        self.bioset_val_input.setGeometry(QtCore.QRect(200, 230, 77, 22))
        self.bioset_val_input.setStyleSheet("QSpinBox {\n"
"    padding-top: 2px;\n"
"    padding-bottom: 2px;\n"
"    border: 1px solid #3A3939;\n"
"    background-color: #201F1F;\n"
"    color: Silver;\n"
"    border-radius: 2px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QSpinBox:up-button\n"
"{\n"
"    background-color: transparent;\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"}\n"
"\n"
"QSpinBox:down-button\n"
"{\n"
"    background-color: transparent;\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"}")
        self.bioset_val_input.setMaximum(999)
        self.bioset_val_input.setObjectName("bioset_val_input")
        self.page3_nextBtn = QtWidgets.QPushButton(self.page_2)
        self.page3_nextBtn.setGeometry(QtCore.QRect(630, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page3_nextBtn.setFont(font)
        self.page3_nextBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.page3_nextBtn.setStyleSheet("QPushButton\n"
"{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
"  transition: all 0.5s;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.page3_nextBtn.setObjectName("page3_nextBtn")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.page4_runBtn = QtWidgets.QPushButton(self.page_3)
        self.page4_runBtn.setGeometry(QtCore.QRect(290, 110, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page4_runBtn.setFont(font)
        self.page4_runBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.page4_runBtn.setStyleSheet("QPushButton\n"
"{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
"  transition: all 0.5s;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.page4_runBtn.setObjectName("page4_runBtn")
        self.page4_backBtn = QtWidgets.QPushButton(self.page_3)
        self.page4_backBtn.setGeometry(QtCore.QRect(20, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page4_backBtn.setFont(font)
        self.page4_backBtn.setStyleSheet("QPushButton\n"
"{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
" \n"
"color: white;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"\n"
"}")
        self.page4_backBtn.setObjectName("page4_backBtn")
        self.small_title_text_3 = QtWidgets.QLabel(self.page_3)
        self.small_title_text_3.setGeometry(QtCore.QRect(350, 0, 61, 16))
        self.small_title_text_3.setObjectName("small_title_text_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.complete_text = QtWidgets.QLabel(self.page_4)
        self.complete_text.setGeometry(QtCore.QRect(305, 30, 141, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        self.complete_text.setFont(font)
        self.complete_text.setObjectName("complete_text")
        self.page5_saveBtn = QtWidgets.QPushButton(self.page_4)
        self.page5_saveBtn.setGeometry(QtCore.QRect(290, 110, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page5_saveBtn.setFont(font)
        self.page5_saveBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.page5_saveBtn.setStyleSheet("QPushButton\n"
"{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
"  transition: all 0.5s;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.page5_saveBtn.setObjectName("page5_saveBtn")
        self.page5_restartBtn = QtWidgets.QPushButton(self.page_4)
        self.page5_restartBtn.setGeometry(QtCore.QRect(630, 490, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.page5_restartBtn.setFont(font)
        self.page5_restartBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.page5_restartBtn.setStyleSheet("QPushButton\n"
"{\n"
"  border-radius: 4px;\n"
"  background-color:    #0080ff;\n"
"  width: 200px;\n"
"  transition: all 0.5s;\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"background-color : green;\n"
"}")
        self.page5_restartBtn.setObjectName("page5_restartBtn")
        self.small_title_text_4 = QtWidgets.QLabel(self.page_4)
        self.small_title_text_4.setGeometry(QtCore.QRect(350, 0, 61, 16))
        self.small_title_text_4.setObjectName("small_title_text_4")
        self.stackedWidget.addWidget(self.page_4)

        self.retranslateUi(View)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(View)

    def retranslateUi(self, View):
        _translate = QtCore.QCoreApplication.translate
        View.setWindowTitle(_translate("View", "Data Direct"))
        self.title_label.setText(_translate("View", "DataDirect"))
        self.page1_nextBtn.setText(_translate("View", "Next"))
        self.textBrowser.setHtml(_translate("View", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"docs-internal-guid-b1a05a49-7fff-97df-5fff-e802f667c518\"></a><span style=\" font-family:\'Calibri\',\'sans-serif\'; font-size:12pt; color:#000000; background-color:transparent;\">S</span><span style=\" font-family:\'Calibri\',\'sans-serif\'; font-size:12pt; color:#000000; background-color:transparent;\">ARS-CoV-2 is an extremely contagious strain of the beta-coronavirus that has infected 87 million people around the world as of January 2021. Through our efforts to provide a guide and novel insights about SARS-CoV-2 from crowdsourcing SARS-CoV public data, we have created this tool to expedite the data wrangling process. </span> </p></body></html>"))
        self.addfilebutton.setText(_translate("View", "+"))
        self.page2_nextBtn.setText(_translate("View", "Next"))
        self.page2_backBtn.setText(_translate("View", "Back"))
        self.addFile_direction.setText(_translate("View", "To proceed, please select a file using the plus button above"))
        self.small_title_text_2.setText(_translate("View", "DataDirect"))
        self.file_status_label.setText(_translate("View", "File:"))
        self.file_status.setText(_translate("View", "Not Selected"))
        self.output_title.setText(_translate("View", "Customize Output"))
        self.analytics_title.setText(_translate("View", "Analytics"))
        self.custom_direct.setText(_translate("View", "Select the columns to be visible in the output spreadsheet\n"
""))
        self.Ana_direct.setText(_translate("View", "Select the Analytics function(s)"))
        self.small_title_text.setText(_translate("View", "DataDirect"))
        self.cust_pval_check.setText(_translate("View", "P-Value"))
        self.cust_actType_check.setText(_translate("View", "Activity Type"))
        self.cust_illuscore_check.setText(_translate("View", "Illumina Score"))
        self.cust_active_score.setText(_translate("View", "Activity Score"))
        self.ana_dis_check.setText(_translate("View", "Directional Illumina Score"))
        self.ana_sum_check.setText(_translate("View", "Sum"))
        self.ana_mean_check.setText(_translate("View", "Mean"))
        self.ana_median_check.setText(_translate("View", "Median"))
        self.ana_std_check.setText(_translate("View", "Standard Deviation"))
        self.ana_centchange_check.setText(_translate("View", "Percent Change Above/Below Control"))
        self.ana_specperc_check.setText(_translate("View", "Specificity as Percentage"))
        self.ana_specint_check.setText(_translate("View", "Specificity as Integer"))
        self.page3_backBtn.setText(_translate("View", "Back"))
        self.bioset_text.setText(_translate("View", "Number of Bioset(s): "))
        self.page3_nextBtn.setText(_translate("View", "Next"))
        self.page4_runBtn.setText(_translate("View", "Run"))
        self.page4_backBtn.setText(_translate("View", "Back"))
        self.small_title_text_3.setText(_translate("View", "DataDirect"))
        self.complete_text.setText(_translate("View", "Complete!"))
        self.page5_saveBtn.setText(_translate("View", "Save"))
        self.page5_restartBtn.setText(_translate("View", "Restart"))
        self.small_title_text_4.setText(_translate("View", "DataDirect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    View = QtWidgets.QWidget()
    ui = Ui_View()
    ui.setupUi(View)
    View.show()
    sys.exit(app.exec_())
